### ISSUE TITLE
Campo 'disponible' no necesario en mensaje multicast

### ISSUE THREAD

**Issue by edwinvrgs** [TemetNosce95/ProtocoloFinalComunicaciones1#1]
Puede que no sea necesario el campo **disponible** en este mensaje:

> El servidor responde al unicast del cliente con un mensaje para confirmar la conexión. Ejemplo:
> ```json
> {
> 	"identificador": "DOMINOCOMUNICACIONESI",
> 	"multicast_ip": "IP multicast definida por el servidor",
> 	"disponible": "Verdadero o falso. Esto es un booleano"
> }
> ```

**Comment by yosswan** [comment]
mientras el cliente decide a que mesa conectarse es probable que otros clientes se conecten a la mesa y la mesa se llene y no este disponible, por lo tanto esta situación justifica la existencia de este mensaje

**Comment by yuleidyvdres** [comment]
Pero si la mesa ya no está disponible simplemente no le llega ese mensaje al cliente que intentó conectarse porque ya su capacidad llegó al límite

**Comment by yosswan** [comment]
y el cliente se quedara esperando hasta que se canse, tambien podrian establecer un tiempo limite y ya

**Comment by yuleidyvdres** [comment]
Si el servidor no le da respuesta se generaría una excepción

**Comment by yosswan** [comment]
quien dijo eso?

**Comment by jesusareyesv** [comment]
Yo creo que simplemente debería manejarse el Connection Refused que genera el intento fallido de conexión. Generar otro handler para el nuevo cliente solo para decirle que no se puede conectar sería mucho problema para luego cerrar la conexión.

**Comment by yosswan** [comment]
Bueno de la forma que yo lo veo es un solo socket el que atiende a todos los clientes, si se hacen multiples sockets para multiples clientes hay que usar multiples puertos

**Comment by jesusareyesv** [comment]
@yosswan TCP no funciona así

**Comment by yosswan** [comment]
si ya me acorde, osea que hay que contemplar mas puertos

**Comment by AlfredoJonas** [comment]
Es que como esta planteado el cliente esta constantemente verificando las mesas(servidores) disponibles, es decir envía broadcast y los servidores que respondan son los que están disponibles, ¿cada cuanto envía? que se yo podría ser cada segundo como bien podría ser cada 5 o 10 segundo eso queda a consideración del programador. Ahora cuando yo decida conectarme a un servidor por tcp solo van a estar disponibles los servidores que tengan mesas disponibles de resto el servidor no va a responder los broadcast que envíen los clientes.

**Comment by jesusareyesv** [comment]
Creo que cuando se llene la mesa simplemente no deberían aceptarse más clientes y que los clientes que reciban el ConnectionRefused deben asumir que la mesa está llena.

**Comment by jesusareyesv** [comment]
Resuelto en 1440fc8df0a79a3b73547077fc7985ea0165b334
