### ISSUE TITLE
¿el mensaje de inicio de juego es unicast?

### ISSUE THREAD

**Issue by yosswan** [TemetNosce95/ProtocoloFinalComunicaciones1#10]
{
	"identificador": "DOMINOCOMUNICACIONESI",
    "tipo" : 0,
    "jugadores": [
        {
            "identificador" : "identificador_jugador_1", 
            "nombre" : "nombre que el jugador 1 le envió al servidor"
        },
        {
            "identificador" : "identificador_jugador_2", 
            "nombre" : "nombre que el jugador 2 le envió al servidor"
        },
        {
            "identificador" : "identificador_jugador_3", 
            "nombre" : "nombre que el jugador 3 le envió al servidor"
        },
        {
            "identificador" : "identificador_jugador_4", 
            "nombre" : "nombre que el jugador 4 le envió al servidor"
        }
    ],
    "jugador" : "Identificador que la mesa genera para el jugador al que le envia estas fichas."
}

**Comment by jesusareyesv** [comment]
Cito textualmente:

> Luego de que se tienen todos los jugadores en la mesa el servidor enviará solo mensajes de juego, dichos mensajes serán multicast (excepto el de asignación de fichas) y se podrán identificar a través de un campo denominado tipo

Entonces, **es multicast** por lo mismo de reducir el tráfico y simplificar la conexión entre el server y los clientes.

**Comment by yosswan** [comment]
pero igual se van a enviar tantos mensajes de inicio de juego como jugadores

**Comment by jesusareyesv** [comment]
Corregido en #11 (commit 9b526427d93967288f14e0e88d575222cf1f01cc)
