### ISSUE TITLE
detalle de incoherencia en tipos de mensaje de servidor

### ISSUE THREAD

**Issue by yosswan** [TemetNosce95/ProtocoloFinalComunicaciones1#12]
Se le olvido actuaizar el tipo en los ejemplos.
ejemplo:

**4 | mensaje de fin de ronda**
-- | --

Mensaje de fin de ronda

Este mensaje indica el final de una ronda, su ganador y su puntuación. Es multicast.

{
	"identificador": "DOMINOCOMUNICACIONESI",
	"jugador": "Identificador del jugador que ganó la ronda",
	**"tipo": 1,**
	"puntuacion": "Puntuación del ganador de la ronda",
	"razon": "Descripción del fin de la ronda. Máximo 45 caracteres"
}

**Comment by jesusareyesv** [comment]
Oks, ahora lo actualizo

**Comment by jesusareyesv** [comment]
Resuelto en 1a5e0e02469b5b0219ecd149b03e5bcf51d4e9b9
