### ISSUE TITLE
Necesidad del campo token

### ISSUE THREAD

**Issue by yosswan** [TemetNosce95/ProtocoloFinalComunicaciones1#2]
> {
            "token": "estoesuntoken",
            "entero_uno": 6,
            "entero_dos": 1
        }

¿Es necesario el token?

**Comment by edwinvrgs** [comment]
Sí, sirve para que el cliente responda solamente con el token, por ahí en
una nota está

**Comment by yosswan** [comment]
no me parece necesario, seria mejor estandarizar el objeto ficha y ya

**Comment by AlfredoJonas** [comment]
@yosswan recuerde que el profesor va a evaluar también la seguridad y los token a nivel de api es muy usado por cuestión de seguridad ya que solo se autentica el usuario una sola vez y es usado por cierto tiempo ese token hasta que este caduca por lo tanto aumenta el nivel de seguridad. En este caso de DOMINOCOMUNICACIONESI no es distinto, en vez de usar los valores de la ficha como tal usamos un token que expira cada vez que se inicia una nueva partida y eso disminuye en gran medida la posibilidad de un ataque a nuestro programa

**Comment by yosswan** [comment]
mmm ok, pero seguridad en que sentido, porque la informacion de la ficha que se juega no es privada, o es para evitar que un agente externo conosca de que forma mandamos las fichas y se haga pasar por un jugador falsificando su ip y envie fichas?

**Comment by AlfredoJonas** [comment]
Si por supuesto cualquier tipo de ataque que se te pueda ocurrir conociendo la estructura y valor de las fichas
