### ISSUE TITLE
Estandarizacion de ficha

### ISSUE THREAD

**Issue by yosswan** [TemetNosce95/ProtocoloFinalComunicaciones1#3]
> {
            "token": "estoesuntoken",
            "entero_uno": 6,
            "entero_dos": 1
    }

> { 
		    "entero_uno": 6, 
    		    "entero_dos": 6
    }

> { 
        "token": "estoesuntoken"  
    }

Deberiamos estandarizar el objeto ficha

**Comment by yosswan** [comment]
mi propuesta es la segunda opcion

**Comment by jesusareyesv** [comment]
Ok, pero el token cómo se generaría?

**Comment by AlfredoJonas** [comment]
No entiendo su propuesta, ¿porque el primer objeto tiene token, el segundo no y el tercero es solo un token?

**Comment by yosswan** [comment]
pero todos son el mismo objeto, una ficha, pero como tiene 3 formas hay que tratar los mensajes de 3 formas diferentes y me parece innecesario
