### ISSUE TITLE
Cambiar la identificación por MAC por identificación por nombre

### ISSUE THREAD

**Issue by jesusareyesv** [TemetNosce95/ProtocoloFinalComunicaciones1#4]
Creo que deberíamos dejar de identificar a los jugadores usando su MAC y empezar a usar el nombre de jugador en su lugar.

**Comment by julia-suarez-deel** [comment]
En vez del nombre de jugador, el servidor deberia asignar un identificador unico cuando manda el mensaje con la IP Multicast, ya que varios jugadores pueden enviar el mismo nombre.

**Comment by jesusareyesv** [comment]
En mi servidor yo tengo a los clientes hasheados con SHA256 para no confundirlos, peeeeero depende de todos cambiar sus programas para que al cosa medio concuerde.

**Comment by AlfredoJonas** [comment]
Puede ser algo como dice @TemetNosce95 porque si no es posible que los clientes escojan un nombre igual, podría funcionar un token generado con SHA, ya la cantidad de bits si se podría estandarizar en el protocolo.

**Comment by yohanacontrerasdev** [comment]
yo estoy de acuerdo con @JSilversun que el servidor cree ese identificador.

**Comment by jesusareyesv** [comment]
Ok, voy a cambiar eso para que la mesa sea la que genere los identificadores.

**Comment by jesusareyesv** [comment]
Issue resuelto en el commit d0e26ee06f9d8e40ce5f4a83e5428631845ed998
