### ISSUE TITLE
Jugador que no está en turno

### ISSUE THREAD

**Issue by loreanazic** [TemetNosce95/ProtocoloFinalComunicaciones1#6]
Según el protocolo actual cada cliente manda un mensaje al servidor de que esta disponible por tcp, el que esta jugando manda su jugada y los otros un mensaje de verificación. Analizando y buscando una manera mas sencilla, me parece mejor que el servidor envié a los clientes que no estén de turno un mensaje para saber si siguen ahí. Si no están conectados se genera una excepción y ya.

**Comment by gregsanz182** [comment]
@loreanazic ¿O sea que enviaría el multicast y el unicast tcp?

**Comment by loreanazic** [comment]
envió el multicast, espero por tcp el mensaje del jugador en turno y después les envió a los otros clientes que no están en turno un unicast por tcp

**Comment by loreanazic** [comment]
pues si me sale la excepción se desconectaron

**Comment by gregsanz182** [comment]
bueno, así está en el protocolo

**Comment by jesusareyesv** [comment]
> envió el multicast, espero por tcp el mensaje del jugador en turno y después les envió a los otros clientes que no están en turno un unicast por tcp

Está hablando acerca del cliente o de la mesa?

**Comment by jesusareyesv** [comment]
Resuelto en 1440fc8df0a79a3b73547077fc7985ea0165b334
