### ISSUE TITLE
¿Porque se repite el envio del identificador unico del jugador?

### ISSUE THREAD

**Issue by AlfredoJonas** [TemetNosce95/ProtocoloFinalComunicaciones1#8]
En el mensaje donde se envía el multicast_ip y el mensaje tipo 0 del servidor se envía el identificador único del jugador, ¿porque?

**Comment by jesusareyesv** [comment]
La verdad es que no supe de cuál de los 2 quitarlo así que lo dejé en ambos mensajes 😆 
Escucho sugerencias por si alguien tiene una mejor opción 😄

**Comment by AlfredoJonas** [comment]
Puede dejarlo, realmente no afecta

**Comment by jesusareyesv** [comment]
Corregido en #11 (commit: 9b526427d93967288f14e0e88d575222cf1f01cc)
